services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - smartshop_net
  
  embedding_model:
    build:
      context: .
      dockerfile: ./embedding_service/Dockerfile # Assuming you created this
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      # Allow overriding the model name via .env file
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-all-MiniLM-L6-v2}
    networks:
      - smartshop_net
    volumes:
      - embedding_model_cache:/app/model_cache # Mount shared cache
    # Add healthcheck for embedding_model if you implement one in its FastAPI app

  vector_db: # <--- NEW QDRANT SERVICE
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"  # gRPC port for client communication
      - "6334:6334"  # REST API port (optional, for web UI or direct REST calls)
    volumes:
      - qdrant_storage:/qdrant/storage # To persist Qdrant data
    networks:
      - smartshop_net
    healthcheck: # Qdrant >= v1.2 uses /readyz
      test: ["CMD-SHELL", "curl -f http://localhost:6333/readyz || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s # Give Qdrant time to start up before checking health
      retries: 5

  
  db_init:
    build:
      context: .
      dockerfile: ./database/Dockerfile_init
    depends_on:
      db:
        condition: service_healthy
      vector_db: # <--- Add dependency on vector_db
        condition: service_started # or service_healthy
    environment:
      # These match what config/config.py expects via os.getenv
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB} # Gets value from root .env's POSTGRES_DB
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Gets value from root .env's POSTGRES_PASSWORD
      # Allow overriding the sentence transformer model used by populate_db.py
      SENTENCE_TRANSFORMER_MODEL: ${EMBEDDING_MODEL_NAME} # If not set in .env, config.py's default will be used
      VECTOR_DB_HOST: vector_db # <--- Hostname for Qdrant
      VECTOR_DB_PORT: ${VECTOR_DB_PORT}    # <--- gRPC port for Qdrant
      PYTHONPATH: /app
    networks:
      - smartshop_net
    volumes:
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./database:/app/database # For init.sql
      - embedding_model_cache:/app/model_cache # Mount shared cache
      - ./data:/app/data
    command: ["python", "/app/scripts/populate_db.py"]

    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      embedding_model:
        condition: service_started # or service_healthy if you add a healthcheck
      vector_db: # <--- Add dependency on vector_db
        condition: service_started # or service_healthy
    environment:
      # For database connection, matching what config/config.py expects
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # For other services
      EMBEDDING_MODEL_URL: ${EMBEDDING_SERVICE_URL}
      VECTOR_DB_HOST: vector_db # <--- Hostname for Qdrant
      VECTOR_DB_PORT: ${VECTOR_DB_PORT}  # <--- gRPC port for Qdrant
      PYTHONPATH: /app # Assuming backend code is in /app/src and this helps imports
    ports:
      - "8000:8000"
    networks:
      - smartshop_net
    volumes:
      - ./backend:/app # Contains src/, etc.

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "80:80" # Or whatever port your frontend uses, e.g., 3000:80 if Next.js uses 3000
#    networks:
#      - smartshop_net
#    depends_on:
#      - backend

networks:
  smartshop_net:
    driver: bridge

volumes:
  db_data:
  qdrant_storage:
  embedding_model_cache: # Define named volume for embedding model cache