FROM python:3.11-slim-bookworm

WORKDIR /app

# Copy the requirements file for the scripts
COPY ./scripts/requirements.txt /app/scripts/requirements.txt

# Install Python dependencies from requirements.txt and add sentence-transformers.
# NLTK-specific configurations, data downloads, and the 'unzip' utility (previously for NLTK) have been removed.
RUN python -m pip install --upgrade pip

RUN python -m pip install \
        --no-cache-dir \
        -r /app/scripts/requirements.txt
