FROM python:3.11-slim-bookworm

WORKDIR /app

# Copy the requirements file for the scripts
COPY ./scripts/requirements.txt /app/scripts/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r /app/scripts/requirements.txt

# Download NLTK data for sentence tokenization
RUN python -m nltk.downloader -d /usr/local/share/nltk_data punkt