FROM python:3.9-slim-buster

# Install psycopg2 and any other dependencies
RUN pip install psycopg2-binary python-dotenv

# Copy the script
COPY ./scripts /app/scripts
COPY ./config /app/config
WORKDIR /app